### ISSUE TITLE
Provide concrete examples of color space transformations

### ISSUE THREAD

**Issue by palemieux** [w3c/ColorWeb-CG#50]
* sRGB to `rec2100-hlg` (see https://www.w3.org/TR/ttml2/#hdr-compositing as a starting point)
* `extended-linear-srgb` to `rec2100-hlg
`

**Comment by simontWork** [comment]
### Conversion from extended-sRGB to HLG

1. Let (r, g, b) be a full-range non-linear floating-point SRGB pixel with black at 0.0 and diffuse white at 1.0.  Values may exist outside the range 0.0 to 1.0.

2. Let (Rh, Gh, Bh) be a full-range non-linear floating-point ITUR-BT2100-HLG pixel with black at 0.0 and diffuse white at 0.75.   Values may exist outside the range 0.0 to 1.0.

3. Linearize using the SRGB EOTF

_(SRGB-EOTF(r),SRGB-EOTF(g),SRGB-EOTF(b)) -> (r,g,b)_

Where:

_SRGB-EOTF(x) = x / 12.92 for 0.0 <= x <= 0.04045_

and

_SRGB-EOTF(x) = ((0.055x)/1.055)<sup>2.4</sup> for x > 0.04045_

and

_SRGB-EOTF(x) = -1.0 x SRGB-EOTF(-1.0x) for x < 0.0_

4. Convert from [SRGB] color space to ITU BT.2100 color space:

_[(0.627404, 0.329283, 0.043313), (0.069097, 0.919540, 0.011362), (0.016391, 0.088013, 0.895595)] . (r, g, b) -> (r, g, b)_

5. Scale pixel values  - SEE NOTE 1

_((0.265r),(0.265g),(0.265b)) -> (r,g,b)_

6. Apply HLG Inverse EOTF to convert to HLG Pseudo-Display Light with Lw = 302 cd/m<sup>2</sup>  - SEE NOTE 1

6a. Step one: apply HLG Inverse OOTF

_(r<sup>1.0</sup>,r<sup>1.0</sup>,r<sup>1.0</sup>) -> (r,g,b)_

6b. Step two: apply HLG OETF  - SEE NOTE 2

_(HLG(r),HLG(g),HLG(b)) -> (Rh,Gh,Bh)_

where

_HLG(x) = (3x)<sup>0.5</sup> for 0 <= x <= 1/12_

and

_HLG(x) = a.ln(12x-b)+c for x > 1/12,_

and

_HLG(x) = -1.0 * HLG(-1.0x) for x < 0.0,_

and 

_a = 0.17883277_ 

and 

_b = 1 - 4a_ 

and 

_c = 0.5 - a.ln(4a)_


**NOTE 1:** As ITU-R BT.2100 HLG is a relative format, the brightness of the virtual monitor used for mathematical transforms can be chosen to be any level.  In this transform it is chosen to be 302 cd/m<sup>2</sup> so that the brightness of diffuse white matches the diffuse white of sRGB (80 cd/m<sup>2</sup>).  Using the extended range gamma formula in footnote 2 of BT.2100, this also sets the HLG Inverse OOTF to be unity.  The value 0.265 is calculated by taking the inverse OETF of 0.75.

**NOTE 2:** See section 5.3 in ITU-R BT.2408-4 relating to negative transfer functions in format conversions.

**Comment by simontWork** [comment]
### Conversion from extended-linear-sRGB to HLG

1. Let (r, g, b) be a full-range linear floating-point SRGB pixel with black at 0.0 and diffuse white at 1.0.  Values may exist outside the range 0.0 to 1.0.

2. Let (Rh, Gh, Bh) be a full-range non-linear floating-point ITUR-BT2100-HLG pixel with black at 0.0 and diffuse white at 0.75.   Values may exist outside the range 0.0 to 1.0.

3. Convert from [SRGB] color space to ITU BT.2100 color space:

_[(0.627404, 0.329283, 0.043313), (0.069097, 0.919540, 0.011362), (0.016391, 0.088013, 0.895595)] . (r, g, b) -> (r, g, b)_

4. Scale pixel values  - SEE NOTE 1

_((0.265r),(0.265g),(0.265b)) -> (r,g,b)_

5. Apply HLG Inverse EOTF to convert to HLG Pseudo-Display Light with Lw = 302 cd/m<sup>2</sup>  - SEE NOTE 1

5a. Step one: apply HLG Inverse OOTF

_(r<sup>1.0</sup>,r<sup>1.0</sup>,r<sup>1.0</sup>) -> (r,g,b)_

5b. Step two: apply HLG OETF  - SEE NOTE 2

_(HLG(r),HLG(g),HLG(b)) -> (Rh,Gh,Bh)_

where

_HLG(x) = (3x)<sup>0.5</sup> for 0 <= x <= 1/12_

and

_HLG(x) = a.ln(12x-b)+c for x > 1/12,_

and

_HLG(x) = -1.0 * HLG(-1.0x) for x < 0.0,_

and 

_a = 0.17883277_ 

and 

_b = 1 - 4a_ 

and 

_c = 0.5 - a.ln(4a)_

**Comment by simontWork** [comment]
### Conversion from HLG to extended-sRGB

1. Let (r, g, b) be a full-range non-linear floating-point ITUR-BT2100-HLG pixel with black at 0.0 and diffuse white at 0.75.  Values may exist outside the range 0.0 to 1.0.

2. Let (Rs, Gs, Bs) be a full-range non-linear floating-point SRGB pixel with black at 0.0 and diffuse white at 1.0.  Values may exist outside the range 0.0 to 1.0.

3. Apply HLG EOTF to convert the non-linear HLG Signal to linear Pseudo-Display Light with Lw = 302 cd/m<sup>2</sup>  - SEE NOTE 1

3a. Step one: apply inverse HLG OETF to derive linear scene light

_(invHLG(r),invHLG(g),invHLG(b)) -> (Rh,Gh,Bh)_

where

_invHLG(x) = x<sup>2.0</sup>/3.0 for 0 <= x <= 0.5_

and

_invHLG(x) =  (exp((x-c)/a)+b)/12.0 for x > 0.5,_
	
and 

_invHLG(x) = -1.0 * invHLG(-1.0*x) for x < 0.0_

and 

_a = 0.17883277_ 

and 

_b = 1 - 4a_ 

and 

_c = 0.5 - a.ln(4a)_

3b. Step two: apply HLG OOTF to derive linear display light

(r<sup>1.0</sup>,g<sup>1.0</sup>,b<sup>1.0</sup>) -> (r,g,b)

4. Scale pixel values

(r/0.265,g/0.265,b/0.265) -> (r,g,b)

5. Convert from [ITU BT.2100-1 color space to SRGB color space:

[(1.660491, -0.58764114, -0.07284986), (-0.12455047, 1.1328999, -0.00834942), (-0.01815076, -0.1005789, 1.11872966)] . (r, g, b) -> (r, g, b)

6. Convert to non-linear SRGB using the SRGB Inverse EOTF

(SRGB-INV-EOTF(r),SRGB-INV-EOTF(g),SRGB-INV-EOTF(b)) -> (Rs,Gs,Bs)

Where:

SRGB-INV-EOTF(x) = 12.92 x for 0.0 <= x <= 0.0031308

and

SRGB-INV-EOTF(x) = (1.055x)<sup>1.0/2.4</sup> - 0.055 for x > 0.0031308

and

SRGB-INV-EOTF(x) = -1.0 x SRGB-EOTF(-1.0x) for x < 0.0

**Comment by simontWork** [comment]
### Conversion from HLG to extended-linear-sRGB

1. Let (r, g, b) be a full-range non-linear floating-point ITUR-BT2100-HLG pixel with black at 0.0 and diffuse white at 0.75.  Values may exist outside the range 0.0 to 1.0.

2. Let (Rs, Gs, Bs) be a full-range linear floating-point SRGB pixel with black at 0.0 and diffuse white at 1.0.  Values may exist outside the range 0.0 to 1.0.

3. Apply HLG EOTF to convert the non-linear HLG Signal to linear Pseudo-Display Light with Lw = 302 cd/m<sup>2</sup>  - SEE NOTE 1

3a. Step one: apply inverse HLG OETF to derive linear scene light

_(invHLG(r),invHLG(g),invHLG(b)) -> (Rh,Gh,Bh)_

where

_invHLG(x) = x<sup>2.0</sup>/3.0 for 0 <= x <= 0.5_

and

_invHLG(x) =  (exp((x-c)/a)+b)/12.0 for x > 0.5,_
	
and 

_invHLG(x) = -1.0 * invHLG(-1.0*x) for x < 0.0_

and 

_a = 0.17883277_ 

and 

_b = 1 - 4a_ 

and 

_c = 0.5 - a.ln(4a)_

3b. Step two: apply HLG OOTF to derive linear display light

(r<sup>1.0</sup>,g<sup>1.0</sup>,b<sup>1.0</sup>) -> (r,g,b)

4. Scale pixel values

(r/0.265,g/0.265,b/0.265) -> (r,g,b)

5. Convert from [ITU BT.2100-1 color space to SRGB color space:

[(1.660491, -0.58764114, -0.07284986), (-0.12455047, 1.1328999, -0.00834942), (-0.01815076, -0.1005789, 1.11872966)] . (r, g, b) -> (Rs,Gs,Bs)

**Comment by simontWork** [comment]
### Suggested Tone-mapping for display of HLG on sRGB Displays  
SEE NOTE 3

1. Let (r, g, b) be a full-range floating-point ITUR-BT2100-HLG pixel with black at 0.0 and diffuse white at 0.75.  Values may exist outside the range 0.0 to 1.0.

2. Let (Rs, Gs, Bs) be a full-range floating-point SRGB pixel with black at 0.0 and diffuse white at 1.0.  Values may exist outside the range 0.0 to 1.0.

3. Linearize the HLG signal exploiting its backwards compatibility with SDR consumer displays

_(r<sup>2.2</sup>,g<sup>2.2</sup>,b<sup>2.2</sup>) -> (r,g,b)_

4. Convert from ITU BT.2100 color space to SRGB color space:

_[(1.660491, -0.58764114, -0.07284986), (-0.12455047, 1.1328999, -0.00834942), (-0.01815076, -0.1005789, 1.11872966)] . (r, g, b) -> (r, g, b)_

5. Convert to SRGB using the SRGB Inverse EOTF

_(SRGB-INV-EOTF(r),SRGB-INV-EOTF(g),SRGB-INV-EOTF(b)) -> (Rs,Gs,Bs)_

Where:

_SRGB-INV-EOTF(x) = 12.92 x for 0.0 <= x <= 0.0031308_

and

_SRGB-INV-EOTF(x) = (1.055x)<sup>1.0/2.4</sup> - 0.055 for x > 0.0031308_

and

_SRGB-INV-EOTF(x) = -1.0 x SRGB-EOTF(-1.0x) for x < 0.0_


**NOTE3:** This transform utilises the backwards compatibility of ITU-R BT.2100 HLG HDR with consumer electronic displays.

**Comment by simontWork** [comment]
@palemieux @svgeesus I'm not sure of the accuracy required for floating point operations in HTML/Canvas/Browsers.  Are there any guidelines?  I can recalculate the matrices if required.

**Comment by simontWork** [comment]
@palemieux I think it would be better if Timo updated this with the PW to sRGB and reverse and the tone mapping operator for displaying a PQ canvas on a sRGB display so he is happy with any adaptation steps.

**Comment by LarsBrg** [comment]
The document should contain no matrix decimals. The actual matrix numbers are an implementation detail, should not be standardized, and should be left to the implementor. You should not penalize someone doing it in double.

Instead state how the matrix is derived from color primaries:
Something like M = Inv(sRGBtoXYZmatrix).Rec2020toXYZmatrix;

Accuracy is irrelevant, as you're using a non-accurate color transform to start with (gamma 2.2 for HLG) so you're guaranteed not to show the same colors as on an HLG reference display.

It would be helpful to know how inaccurately the colors within the sRGB gamut will be transformed compared to an HLG reference display.

**Comment by jdashg** [comment]
Yes please, demonstrating derivation is better than here-are-some-numbers.
(also js-like pseudocode (rather than algebraic notation) is best, for this web tech field)
We're definitely talking method more than actual implementation here.
