### ISSUE TITLE
`cICP` and `sRGB`

### ISSUE THREAD

**Issue by svgeesus** [w3c/ColorWeb-CG#54]
I'm mainly thinking about allowed, disallowed chunk combinations, and priority of chunks where there is a potential conflict.

From [Adding support for HDR imagery to the PNG format](https://github.com/w3c/ColorWeb-CG/blob/master/hdr-in-png-requirements.md)

> A PNG datastream shall contain at most one embedded profile, whether specified explicitly with an iCCP or iCCN chunk or implicitly with an sRGB chunk.

This raises an interesting distinction between a color profile (which provides numerical data about a color space, but does not name it) and a color space description (which names, but relies on external knowledge for the numerical data).

For example, given two ICC profiles, which declare the same (or very similar) primary chromaticities and whitepoint, and very similar transfer function (but there are many ways that could be expressed - as a LUT, and a parametric function, etc) are these **the same colorspace**

The answer has to be "no" or at least "we don't know"; while for labeling schemes, given two labels, they unambiguously either are or are not the same.

`cICP` is clearly labeling, and `iCCP` and `iCCN` are clearly profiles. I had always considered `sRGB` to be labeling and thus, similar to `cICP` except that it conveys only one colorspace option instead of many. The current text considers `sRGB` to be an implicit color profile. I think it does so primarily to constrain the combinations of chunks. According to that logic isn't `cICP` also an implicit profile?

I seems to me that if there are two PNG files, one has `sRGB` and the other has `cICP` with values 1/13/0/1 then they are both unambiguously labeled as the sRGB color space. The proposal says you can have both, but then the `sRGB` must be ignored.

I don't think `sRGB` should be described as an implicit profile, now that we have the concept of color space labelling.

**Comment by ProgramMax** [comment]
I agree.
I like your idea of "color space label / profile". IE a label is a profile the other side already knows.

I think the wording of "shall contain at most one ... profile" (implicit or not) is too strict.

During a transition period, I could imagine a file containing both an iCCN and iCCP chunk. The iCCN chunk is most correct. But perhaps the iCCP chunk is close enough for jazz. And since it is a transition period, maybe having a fallback for clients that don't yet support iCCN is worth it.

That's the explicit case. For implicit profiles (labels), it seems even more true to me.

I think it is better for us to only spell out the chunk priority.
What would an image viewer do if it encountered an image with both iCCN and iCCP chunks? It already knows the priority. Should it error? Surely not. Surely it should just stick with the priority and ignore the other chunks.

I'll write up a pull request to clean this up.
